name       : gflags
version    : 2.1.2
release    : 1
source     :
    - https://github.com/gflags/gflags/archive/v2.1.2.tar.gz : d8331bd0f7367c8afd5fcb5f5e85e96868a00fd24b7276fa5fcee1e5575c2662
license    : BSD-3-Clause
component  : programming
summary    : C++ library that implements commandline flags processing
description: |
    The gflags package contains a C++ library that implements commandline flags processing. It includes built-in support for standard types such as string and the ability to define flags in the source file in which they are used.
setup      : |
    %cmake -DBUILD_SHARED_LIBS=ON \
           -DLIB_SUFFIX=%LIBSUFFIX% .
build      : |
    %make
install    : |
    %make_install
